import { Badge } from "@/components/ui/badge"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { getRatingConfidence, getRatingStatusLabel } from "@/lib/ratings/confidence"
import { POSITION_LABELS, PLAYER_POSITIONS, type PlayerPosition } from "@/lib/ratings/types"
import { updatePlayerPositionRating } from "@/lib/players/mutations"

type Rating = { position: PlayerPosition; rating: number; initialRating: number; gamesPlayed: number; wins: number; draws: number; losses: number; isEligible: boolean; preferenceOrder: number | null }

export function PlayerRatingCard({ player, canManage }: { player: { id: number; name: string; ratings: Record<PlayerPosition, Rating> }; canManage: boolean }) {
  const enabled = PLAYER_POSITIONS.filter((p) => player.ratings[p].isEligible)
  const main = PLAYER_POSITIONS.find((p) => player.ratings[p].preferenceOrder === 1)
  return <Card><CardHeader><CardTitle className="flex items-center justify-between text-lg"><span>{player.name}</span>{enabled.length === 0 && <Badge variant="destructive">Keine Position</Badge>}</CardTitle><p className="text-sm text-muted-foreground">Hauptposition: {main ? POSITION_LABELS[main] : "Nicht gesetzt"}</p></CardHeader><CardContent className="grid gap-3 md:grid-cols-3">{PLAYER_POSITIONS.map((position) => { const r = player.ratings[position]; return <div key={position} className="rounded-lg border p-3"><div className="mb-2 flex items-center justify-between"><strong>{POSITION_LABELS[position]}</strong><Badge variant={r.isEligible ? "default" : "secondary"}>{r.isEligible ? "Freigeschaltet" : "Gesperrt"}</Badge></div><p className="text-sm">Rating {r.rating}</p><p className="text-sm text-muted-foreground">{r.gamesPlayed} Spiele · {getRatingStatusLabel(r.gamesPlayed)}</p><p className="text-sm text-muted-foreground">Konfidenz {Math.round(getRatingConfidence(r.gamesPlayed) * 100)} %</p>{canManage && <form action={updatePlayerPositionRating} className="mt-3 grid gap-2 text-sm"><input type="hidden" name="playerId" value={player.id} /><input type="hidden" name="position" value={position} /><label className="flex items-center gap-2"><input type="checkbox" name="isEligible" defaultChecked={r.isEligible} /> spielbar</label><label>Präferenz<select name="preferenceOrder" defaultValue={r.preferenceOrder ?? ""} className="mt-1 w-full rounded-md border bg-background px-2 py-1"><option value="">Keine</option><option value="1">Hauptposition</option><option value="2">Nebenposition 1</option><option value="3">Nebenposition 2</option></select></label><label>Start-Rating<input name="initialRating" type="number" min="100" defaultValue={r.initialRating} className="mt-1 w-full rounded-md border bg-background px-2 py-1" /></label><button className="rounded-md bg-primary px-2 py-1 text-primary-foreground">Speichern</button></form>}</div>})}</CardContent></Card>
}
