import { DEFAULT_MATCHMAKING_SETTINGS, MATCHMAKING_SETTING_FIELDS } from "@/lib/matchmaking/settings"
import { ACTIVE_SLOTS_PER_POSITION, MAX_ACTIVE_PLAYERS_PER_TEAM, TEAM_NUMBERS } from "@/lib/matchmaking/rules"
import { GENETIC_TIME_SHARE, MATCHMAKING_QUALITY_THRESHOLDS, MAX_OPTIONAL_LOCAL_CANDIDATES, OPTIONAL_LOCAL_CANDIDATE_SHARE, POSITION_PREFERENCE_PENALTIES } from "@/lib/matchmaking/constants"
import { DEFAULT_RATING, INITIAL_RATING_OPTIONS, MINIMUM_RATING, ROTATION_BONUS_PER_SUBSTITUTE } from "@/lib/ratings/constants"

export type HelpLocale = "de" | "en"
export type HelpTableRow = { label: string; value: string; meaning?: string; numericValues: number[]; valueIsFormula?: boolean }
export type HelpTable = { id: string; title: string; headings: [string, string, string?]; note?: string; after?: string; rows: HelpTableRow[] }

const nf = (locale: HelpLocale) => new Intl.NumberFormat(locale === "de" ? "de-DE" : "en-US")
function n(locale: HelpLocale, value: number) { return nf(locale).format(value) }
function field(key: keyof typeof DEFAULT_MATCHMAKING_SETTINGS) { return MATCHMAKING_SETTING_FIELDS.find((item) => item.key === key)! }

export const MATCHMAKING_PRIORITY_ORDER = {
  de: ["Harte Regelverletzungen", "Machbare Ziel-Aufstellung", "Aktive-Spieler-Balance", "Effektive Teamstärke-Differenz", "Positionsstärke-Differenz", "Startaufstellung-Differenz", "Wechselspieler-Balance", "Passende Wechselgruppen", "Rotationsspreizung", "Positionsdrang", "Positionswünsche", "Rating-Vertrauen", "Balance nicht eingestufter Personen"],
  en: ["Hard violations", "Feasible target lineup", "Active-player balance", "Effective team-strength difference", "Position-strength difference", "Starting-lineup difference", "Substitute balance", "Rotation matching", "Rotation spread", "Position crowding", "Position preferences", "Rating confidence", "Unrated-player balance"],
} as const

export function buildMatchmakingHelpTables(locale: HelpLocale): HelpTable[] {
  const de = locale === "de"
  const maxCandidates = field("maxCandidates"), generations = field("maxGenerations"), population = field("populationSize"), time = field("maxComputationTimeMs")
  return [
    { id: "lineup", title: de ? "Aufstellung und Teamstärke" : "Lineup and team strength", headings: de ? ["Regel", "Wert oder Formel", "Bedeutung"] : ["Rule", "Value or formula", "Meaning"], rows: [
      { label: de ? "Mannschaften" : "Teams", value: String(TEAM_NUMBERS.length), meaning: de ? "Team Blau und Team Weiß" : "Team Blue and Team White", numericValues: [TEAM_NUMBERS.length] },
      { label: de ? "Maximale Teamgrößen-Differenz" : "Maximum team-size difference", value: de ? "1 Person" : "1 player", meaning: de ? "Bei gerader Teilnehmerzahl gleich groß, bei ungerader Zahl höchstens eine Person Unterschied" : "Equal sizes for an even roster; at most one player difference for an odd roster", numericValues: [1] },
      { label: de ? "Aktive Personen pro vollständigem Team" : "Active players per complete team", value: String(MAX_ACTIVE_PLAYERS_PER_TEAM), meaning: de ? "Es starten höchstens sechs Personen im Wasser" : "At most six players start in the water", numericValues: [MAX_ACTIVE_PLAYERS_PER_TEAM] },
      { label: de ? "Torwart-Slots" : "Goalkeeper slots", value: String(ACTIVE_SLOTS_PER_POSITION.goalkeeper), meaning: de ? "Zwei unabhängige Wechselplätze" : "Two independent rotation places", numericValues: [ACTIVE_SLOTS_PER_POSITION.goalkeeper] },
      { label: de ? "Verteidiger-Slots" : "Defender slots", value: String(ACTIVE_SLOTS_PER_POSITION.defender), meaning: de ? "Zwei unabhängige Wechselplätze" : "Two independent rotation places", numericValues: [ACTIVE_SLOTS_PER_POSITION.defender] },
      { label: de ? "Stürmer-Slots" : "Forward slots", value: String(ACTIVE_SLOTS_PER_POSITION.forward), meaning: de ? "Zwei unabhängige Wechselplätze" : "Two independent rotation places", numericValues: [ACTIVE_SLOTS_PER_POSITION.forward] },
      { label: de ? "Starter pro besetztem Slot" : "Starters per populated slot", value: "1", meaning: de ? "Jeder Wechsel-Slot hat genau eine startende Person" : "Every rotation slot has exactly one starter", numericValues: [1] },
      { label: de ? "Wechselspieler-Bonus" : "Substitute bonus", value: `+${ROTATION_BONUS_PER_SUBSTITUTE} ${de ? "effektive MMR" : "effective MMR"}`, meaning: de ? "Für jede zusätzliche Person innerhalb eines Wechsel-Slots" : "For every additional member in a rotation slot", numericValues: [ROTATION_BONUS_PER_SUBSTITUTE] },
      { label: de ? "Effektive Slot-MMR" : "Effective slot MMR", value: de ? `höchste Positions-MMR + ${ROTATION_BONUS_PER_SUBSTITUTE} × Anzahl der Wechselspieler` : `highest position MMR + ${ROTATION_BONUS_PER_SUBSTITUTE} × substitute count`, meaning: de ? "Ein schwacher Wechselspieler kann den Slot nicht schwächer machen" : "A weaker substitute cannot make the slot weaker", numericValues: [ROTATION_BONUS_PER_SUBSTITUTE], valueIsFormula: true },
      { label: de ? "Effektive Team-MMR" : "Effective team MMR", value: de ? "Durchschnitt aller besetzten Slot-MMRs" : "average of all populated slot MMRs", meaning: de ? "Bei vollständiger Aufstellung der Durchschnitt der sechs aktiven Slots" : "For a complete lineup, the average of the six active slots", numericValues: [MAX_ACTIVE_PLAYERS_PER_TEAM], valueIsFormula: true },
      { label: de ? "Ø Spieler-MMR" : "Average player MMR", value: de ? "Durchschnitt der zugeordneten Positions-MMR aller Teammitglieder" : "average assigned-position MMR of every team member", meaning: de ? "Reiner Teilnehmerdurchschnitt; nicht die vom Optimierer verwendete Teamstärke" : "Participant average only; not the optimized team strength", numericValues: [], valueIsFormula: true },
    ] },
    { id: "preferences", title: de ? "Spielbarkeit und Positionswunsch" : "Eligibility and position preference", headings: de ? ["Regel", "Wert oder Formel", "Bedeutung"] : ["Rule", "Value or formula", "Meaning"], note: de ? "Die folgenden Präferenzwerte sind interne Vergleichspunkte und keine MMR." : "The following preference values are internal comparison points, not MMR.", after: de ? "Gültige Aufstellung, Teamstärke, Positionsbalance und Startaufstellung werden vor Positionswünschen verglichen." : "Valid lineup, effective team strength, position balance and starting lineup are compared before position preferences.", rows: [
      { label: de ? "Hauptposition, Rang 1" : "Main position, rank 1", value: n(locale, POSITION_PREFERENCE_PENALTIES.main), meaning: de ? "Wird bevorzugt" : "Preferred", numericValues: [POSITION_PREFERENCE_PENALTIES.main] },
      { label: de ? "Erste Nebenposition, Rang 2" : "First secondary position, rank 2", value: n(locale, POSITION_PREFERENCE_PENALTIES.secondaryRank2), meaning: de ? "Spielbar, aber weniger bevorzugt" : "Eligible but less preferred", numericValues: [POSITION_PREFERENCE_PENALTIES.secondaryRank2] },
      { label: de ? "Zweite Nebenposition, Rang 3" : "Second secondary position, rank 3", value: n(locale, POSITION_PREFERENCE_PENALTIES.secondaryRank3), meaning: de ? "Spielbar, aber deutlich weniger bevorzugt" : "Eligible but substantially less preferred", numericValues: [POSITION_PREFERENCE_PENALTIES.secondaryRank3] },
      { label: de ? "Spielbar ohne Präferenzrang" : "Eligible without a preference rank", value: n(locale, POSITION_PREFERENCE_PENALTIES.eligibleUnranked), meaning: de ? "Technischer Notfallwert" : "Technical fallback value", numericValues: [POSITION_PREFERENCE_PENALTIES.eligibleUnranked] },
      { label: de ? "Nicht spielbar" : "Ineligible position", value: de ? `${n(locale, POSITION_PREFERENCE_PENALTIES.ineligible)} plus harte Regelverletzung` : `${n(locale, POSITION_PREFERENCE_PENALTIES.ineligible)} plus a hard violation`, meaning: de ? "Darf nicht zugewiesen werden" : "Must not be assigned", numericValues: [POSITION_PREFERENCE_PENALTIES.ineligible] },
    ] },
    { id: "ratings", title: de ? "Ratings und Vertrauen" : "Ratings and confidence", headings: de ? ["Regel", "Wert oder Formel", "Bedeutung"] : ["Rule", "Value or formula", "Meaning"], rows: [
      { label: de ? "Standard-MMR" : "Default MMR", value: n(locale, DEFAULT_RATING), meaning: de ? "Standardwert ohne konfigurierte Anfangsbewertung" : "Default when no initial rating is configured", numericValues: [DEFAULT_RATING] },
      { label: de ? "Minimale MMR" : "Minimum MMR", value: n(locale, MINIMUM_RATING), meaning: de ? "Ein Rating kann nicht darunter fallen" : "A rating cannot fall below this", numericValues: [MINIMUM_RATING] },
      { label: de ? "Wählbare Anfangs-MMR" : "Available initial MMR", value: INITIAL_RATING_OPTIONS.map((v) => n(locale, v)).join(" / "), meaning: de ? "Verfügbare Startwerte" : "Available starting values", numericValues: [...INITIAL_RATING_OPTIONS] },
      { label: de ? "Noch nicht eingestuft" : "Unrated", value: de ? "0–4 Spiele" : "0–4 games", meaning: de ? "Sehr unsicheres Rating" : "Very uncertain rating", numericValues: [0, 4] },
      { label: de ? "Vorläufig" : "Provisional", value: de ? "5–14 Spiele" : "5–14 games", meaning: de ? "Rating wird zuverlässiger" : "Rating is becoming more reliable", numericValues: [5, 14] },
      { label: de ? "Eingestuft" : "Established", value: de ? "ab 15 Spielen" : "15 or more games", meaning: de ? "Rating gilt als etabliert" : "Rating is considered established", numericValues: [15] },
      { label: de ? "Rating-Vertrauen" : "Rating confidence", value: de ? "Spiele ÷ 15, maximal 100 %" : "games ÷ 15, capped at 100%", meaning: de ? "Wird zwischen den Teams möglichst gleich verteilt" : "Distributed between teams as evenly as possible", numericValues: [15, 1], valueIsFormula: true },
    ] },
    { id: "search", title: de ? "Sucheinstellungen" : "Search settings", headings: de ? ["Regel", "Wert oder Formel", "Bedeutung"] : ["Rule", "Value or formula", "Meaning"], rows: [
      { label: de ? "Maximale Kandidaten" : "Maximum candidates", value: `${de ? "Standard" : "default"} ${n(locale, DEFAULT_MATCHMAKING_SETTINGS.maxCandidates)}`, meaning: `${n(locale, maxCandidates.min)}–${n(locale, maxCandidates.max)}, ${de ? "Schritte zu" : "steps of"} ${n(locale, maxCandidates.step)}`, numericValues: [DEFAULT_MATCHMAKING_SETTINGS.maxCandidates, maxCandidates.min, maxCandidates.max, maxCandidates.step] },
      { label: de ? "Generationen" : "Generations", value: `${de ? "Standard" : "default"} ${n(locale, DEFAULT_MATCHMAKING_SETTINGS.maxGenerations)}`, meaning: `${n(locale, generations.min)}–${n(locale, generations.max)}, ${de ? "Schritte zu" : "steps of"} ${n(locale, generations.step)}`, numericValues: [DEFAULT_MATCHMAKING_SETTINGS.maxGenerations, generations.min, generations.max, generations.step] },
      { label: de ? "Population" : "Population", value: `${de ? "Standard" : "default"} ${n(locale, DEFAULT_MATCHMAKING_SETTINGS.populationSize)}`, meaning: `${n(locale, population.min)}–${n(locale, population.max)}, ${de ? "Schritte zu" : "steps of"} ${n(locale, population.step)}`, numericValues: [DEFAULT_MATCHMAKING_SETTINGS.populationSize, population.min, population.max, population.step] },
      { label: de ? "Zeitlimit" : "Time limit", value: `${de ? "Standard" : "default"} ${n(locale, DEFAULT_MATCHMAKING_SETTINGS.maxComputationTimeMs)} ms`, meaning: `${n(locale, time.min)}–${n(locale, time.max)} ms, ${de ? "Schritte zu" : "steps of"} ${n(locale, time.step)}`, numericValues: [DEFAULT_MATCHMAKING_SETTINGS.maxComputationTimeMs, time.min, time.max, time.step] },
      { label: de ? "Genetische Suchphase" : "Genetic search phase", value: de ? `maximal ${Math.round(GENETIC_TIME_SHARE * 100)} % des Zeitlimits` : `at most ${Math.round(GENETIC_TIME_SHARE * 100)}% of the time limit`, meaning: de ? "Die restliche Zeit bleibt für lokale Verbesserungen" : "Remaining time is available for local improvement", numericValues: [GENETIC_TIME_SHARE], valueIsFormula: true },
      { label: de ? "Erster positionsgleicher Tauschdurchlauf" : "First same-position swap sweep", value: de ? "maximal ⌊Spieler² ÷ 4⌋ Kandidaten" : "at most ⌊players² ÷ 4⌋ candidates", meaning: de ? "Bei 30 Personen höchstens 225 Tausche" : "At most 225 swaps for 30 players", numericValues: [4, 30, 225], valueIsFormula: true },
      { label: de ? "Optionale lokale Reserve" : "Optional local reserve", value: de ? `maximal ${Math.round(OPTIONAL_LOCAL_CANDIDATE_SHARE * 100)} %, höchstens ${MAX_OPTIONAL_LOCAL_CANDIDATES} Kandidaten` : `at most ${Math.round(OPTIONAL_LOCAL_CANDIDATE_SHARE * 100)}%, capped at ${MAX_OPTIONAL_LOCAL_CANDIDATES} candidates`, meaning: de ? "Wird nur reserviert, wenn genügend Gesamtbudget vorhanden ist" : "Reserved only when the total budget permits it", numericValues: [OPTIONAL_LOCAL_CANDIDATE_SHARE, MAX_OPTIONAL_LOCAL_CANDIDATES], valueIsFormula: true },
    ] },
    { id: "quality", title: de ? "Ergebnisqualität" : "Result quality label", headings: de ? ["Regel", "Bedeutung"] : ["Rule", "Meaning"], rows: [
      { label: de ? "Hoch" : "High", value: de ? `Keine Warnung, effektive MMR-Differenz höchstens ${MATCHMAKING_QUALITY_THRESHOLDS.highMaximumStrengthDifference} und höchstens ein Drittel der Ratings instabil` : `No warning, effective MMR difference at most ${MATCHMAKING_QUALITY_THRESHOLDS.highMaximumStrengthDifference} and no more than one third of ratings unstable`, numericValues: [MATCHMAKING_QUALITY_THRESHOLDS.highMaximumStrengthDifference, MATCHMAKING_QUALITY_THRESHOLDS.maximumUnstableFraction] },
      { label: de ? "Mittel" : "Medium", value: de ? `Effektive MMR-Differenz ${MATCHMAKING_QUALITY_THRESHOLDS.highMaximumStrengthDifference + 1}–${MATCHMAKING_QUALITY_THRESHOLDS.lowAboveStrengthDifference} oder mehr als ein Drittel der Ratings instabil` : `Effective MMR difference from ${MATCHMAKING_QUALITY_THRESHOLDS.highMaximumStrengthDifference + 1} to ${MATCHMAKING_QUALITY_THRESHOLDS.lowAboveStrengthDifference} or more than one third of ratings unstable`, numericValues: [MATCHMAKING_QUALITY_THRESHOLDS.highMaximumStrengthDifference + 1, MATCHMAKING_QUALITY_THRESHOLDS.lowAboveStrengthDifference, MATCHMAKING_QUALITY_THRESHOLDS.maximumUnstableFraction] },
      { label: de ? "Niedrig" : "Low", value: de ? `Mindestens eine Warnung oder effektive MMR-Differenz größer als ${MATCHMAKING_QUALITY_THRESHOLDS.lowAboveStrengthDifference}` : `At least one warning or an effective MMR difference above ${MATCHMAKING_QUALITY_THRESHOLDS.lowAboveStrengthDifference}`, numericValues: [MATCHMAKING_QUALITY_THRESHOLDS.lowAboveStrengthDifference] },
    ] },
  ]
}
